# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/Greeter/add',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorReply.FromString,
                )
        self.multiply = channel.unary_unary(
                '/Greeter/multiply',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorReply.FromString,
                )
        self.divide = channel.unary_unary(
                '/Greeter/divide',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorReply.FromString,
                )
        self.subtract = channel.unary_unary(
                '/Greeter/subtract',
                request_serializer=calculator__pb2.CalculatorRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def multiply(self, request, context):
        """Sends another greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorReply.SerializeToString,
            ),
            'multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.multiply,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorReply.SerializeToString,
            ),
            'divide': grpc.unary_unary_rpc_method_handler(
                    servicer.divide,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorReply.SerializeToString,
            ),
            'subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.subtract,
                    request_deserializer=calculator__pb2.CalculatorRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/add',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/multiply',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/divide',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/subtract',
            calculator__pb2.CalculatorRequest.SerializeToString,
            calculator__pb2.CalculatorReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
